### ISSUE TITLE
Computer wiedererkennen mit Cookie

### ISSUE THREAD

**Issue by denis-kasak** [denis-kasak/uni-webdev#15]
Szenario: Cassidy ruft die Webanwendung erneut auf

Gegeben sei das Cassidy die Webanwendung schon einmal erfolgreich aufgerufen hat.
Wenn die Anwendung vollständig geladen wurde,
dann wird Cassidy's Anwesenheit durch ein Merkmal auch nach dem schließen des Browsers wiedererkannt.

**Comment by instantcreator** [comment]
Der Usercookie hat ein expiredate von max_Save_int. Bitte prüfen @denis-kasak, ob das so ok ist. Wenn ja, issue schließen.

**Comment by denis-kasak** [comment]
passt
