### ISSUE TITLE
meistbesuche Inhalte anzeigen

### ISSUE THREAD

**Issue by denis-kasak** [denis-kasak/uni-webdev#16]
Szenario: Cassidy ruft die Webanwendung erneut auf

Gegeben sei das Cassidy die Webanwendung schon einmal erfolgreich aufgerufen hat.
Wenn die Startseite vollständig geladen wurde,
dann werden Cassidy ihre meist besuchten Inhalte angezeigt.

**Comment by instantcreator** [comment]
Wir benötigen dafür einen dedizierten Bereich auf der Startseite. Bitte noch jemand vom Frontendteam assignen.

**Comment by instantcreator** [comment]
Meist besuchte Seiten werden angezeigt. evtl. kann das System noch etwas schöner im Design gemacht werden.

**Comment by denis-kasak** [comment]
Issues bitte erst schließen, wenn sie im main-branch sind

**Comment by instantcreator** [comment]
ok, kommt alles gleich nach main.
