### ISSUE TITLE
Kommentare mit Username

### ISSUE THREAD

**Issue by denis-kasak** [denis-kasak/uni-webdev#19]
Szenario: Cassidy ruft die Webanwendung erneut auf

Gegeben sei das Cassidy bereits Kommentare erstellt hat.
Wenn eine Inhaltsseite vollständig geladen wurde,
dann werden Cassidy ihre Kommentare anhand ihres Personalisierungsmerkmals angezeigt.

**Comment by instantcreator** [comment]
Max, bitte generiere ggf. mit dem Frontendteam eine Profilseite. Ich werde demnächst dafür dann die Backend Funktionen schreiben.

**Comment by instantcreator** [comment]
Die Version, welche gerade in Server drin ist sollte passen. Ihr werden jetzt alle Kommentare mit Nutzername oder als Anonym angezeigt und sie sieht, welche Kommentare von ihr sind. In Zukunft werden unter Profil alle Kommentar, welche Cassy geschrieben hat angezeigt

**Comment by timgndrmnn** [comment]
sqlmodules wurde für dieses issue angepasst vom Backend-Team.
