### ISSUE TITLE
Vergleichsseite: persönliche Favoriten anzeigen

### ISSUE THREAD

**Issue by denis-kasak** [denis-kasak/uni-webdev#20]
Szenario: Cassidy ruft die Webanwendung erneut auf

Gegeben sei das Cassidy bereits Inhalte als Favorit markiert hat.
Wenn eine Inhaltsseite vollständig geladen wurde,
dann werden Cassidy ihre favorisierten Inhalte anhand ihres Personalisierungsmerkmals angezeigt.

**Comment by instantcreator** [comment]
Bitte noch jemand aus dem Frontendteam für die Profilseite assignen.(Max, habe dich hier mal stellvertetend assigned, sprech das bitte mit dem Frontendteam ab.)
Teil der Profilseite. Wir benötigen dafür einen eigenen Bereich, in dem dann aus dem Backend die Favouriten mitgegeben werden.
