### ISSUE TITLE
Kommentare ohne Nutzernamen

### ISSUE THREAD

**Issue by instantcreator** [denis-kasak/uni-webdev#36]
Kommentare ohne Nutzernamen sollten vom Nutzer Anonym + Datenbankid des Nutzers sein.

**Comment by denis-kasak** [comment]
Meiner Meinung nach nur Anonym. Datenbank ID sollte nichts im Frontend zu suchen haben

**Comment by instantcreator** [comment]
Es gilt hier nur eine generische Unterscheidbare Nummer zu haben. Die Datenbankid ist hier gut, da Sie verschiedene Annonyme Nutzer unterscheiden kann und der selbe Anonyme Nutzer wiederzuerkennnen ist.

**Comment by instantcreator** [comment]
Ist gemacht und wird demnächst auf main gepusht.
